import 'package:flutter_patcher_core/flutter_patcher_core.dart';
import 'package:test/test.dart';

/// Ground-truth values generated by executing hot-updater's actual
/// rollout.ts logic under node (see scripts/verify_rollout.mjs).
void main() {
  group('ground-truth vectors (TS-verified)', () {
    test('getDefaultNumericCohort matches TS', () {
      expect(getDefaultNumericCohort('device-abc-123'), '809');
      expect(getDefaultNumericCohort('ANDROID_ID_SAMPLE_42'), '64');
      expect(getDefaultNumericCohort('8f2a1b6c'), '996');
    });

    test('shuffle parameters match TS', () {
      expect(getNumericCohortRolloutPosition('bundle-a', 1), 309);
      expect(getNumericCohortRolloutPosition('bundle-a', 500), 228);
      expect(getNumericCohortRolloutPosition('bundle-b', 999), 816);
    });

    test('rolled-out cohort sets match TS', () {
      final a137 = getRolledOutNumericCohorts('bundle-a', 137);
      expect(a137.take(3), [4, 11, 16]);
      expect(a137.skip(a137.length - 3), [980, 985, 992]);
      expect(a137.length, 137);

      final b100 = getRolledOutNumericCohorts('bundle-b', 100);
      expect(b100.take(3), [1, 14, 22]);
    });
  });

  group('getRolledOutNumericCohorts (spec cases)', () {
    test('ascending unique set matching eligibility', () {
      final cohorts = getRolledOutNumericCohorts('x-bundle', 137);
      expect(cohorts.length, 137);
      expect(cohorts, [...cohorts]..sort());
      expect(cohorts.toSet().length, 137);
      for (final c in cohorts) {
        expect(isCohortEligibleForUpdate('x-bundle', '$c', 137, null), isTrue);
      }
      final excluded = List.generate(1000, (i) => i + 1)
          .firstWhere((c) => !cohorts.contains(c));
      expect(
        isCohortEligibleForUpdate('x-bundle', '$excluded', 137, null),
        isFalse,
      );
    });

    test('expanding rollout keeps existing cohorts', () {
      final small = getRolledOutNumericCohorts('y-bundle', 100).toSet();
      final large = getRolledOutNumericCohorts('y-bundle', 400);
      expect(large.length, 400);
      expect(large.toSet().containsAll(small), isTrue);
    });

    test('boundaries', () {
      expect(getRolledOutNumericCohorts('z-bundle', 0), isEmpty);
      expect(getRolledOutNumericCohorts('z-bundle', 1000).length, 1000);
      expect(getRolledOutNumericCohorts('z-bundle', -5), isEmpty);
    });
  });

  group('isCohortEligibleForUpdate (spec cases)', () {
    test('numeric rollout stays active with target cohorts configured', () {
      const bundleId = 'd-bundle';
      final cohorts = getRolledOutNumericCohorts(bundleId, 137);
      expect(
        isCohortEligibleForUpdate(
            bundleId, '${cohorts.first}', 137, ['qa-group']),
        isTrue,
      );
    });

    test('targeted custom cohort included beyond percentage', () {
      expect(
        isCohortEligibleForUpdate('e-bundle', 'qa-group', 137, ['qa-group']),
        isTrue,
      );
    });

    test('targeted numeric cohort wins even when excluded by rollout', () {
      const bundleId = 'f-bundle';
      final rolledOut = getRolledOutNumericCohorts(bundleId, 10).toSet();
      final excluded = List.generate(1000, (i) => i + 1)
          .firstWhere((c) => !rolledOut.contains(c));
      expect(
        isCohortEligibleForUpdate(bundleId, '$excluded', 10, ['$excluded']),
        isTrue,
      );
    });

    test('null cohort: eligible only at full rollout', () {
      expect(isCohortEligibleForUpdate('g-bundle', null, 500, null), isFalse);
      expect(isCohortEligibleForUpdate('g-bundle', null, null, null), isTrue);
      expect(isCohortEligibleForUpdate('g-bundle', null, 0, null), isFalse);
    });

    test('custom cohorts never match percentage rollouts', () {
      expect(isCohortEligibleForUpdate('h-bundle', 'qa-team', 999, null),
          isFalse);
      expect(
        isCohortEligibleForUpdate('h-bundle', 'qa-team', 999, ['qa-team']),
        isTrue,
      );
    });
  });

  group('cohort validation (spec cases)', () {
    test('rejects empty and out-of-range numeric strings', () {
      expect(isValidCohort(''), isFalse);
      expect(isValidCohort('1001'), isFalse);
      expect(isCustomCohort('1001'), isFalse);
    });

    test('enforces max custom length', () {
      expect(isValidCohort('a' * maxCohortLength), isTrue);
      expect(isValidCohort('a' * (maxCohortLength + 1)), isFalse);
    });

    test('message mentions limit', () {
      expect(invalidCohortErrorMessage.contains('$maxCohortLength'), isTrue);
    });

    test('normalization trims and lowercases', () {
      expect(normalizeCohortValue('  QA-Group '), 'qa-group');
      expect(normalizeCohortValue('007'), '7');
    });
  });
}
