import 'dart:convert';
import 'dart:io';

import 'package:flutter_ota_kit_core/flutter_ota_kit_core.dart';
import 'package:test/test.dart';

/// Ground truth generated by executing the REAL verkit package
/// (hot-updater's semver dependency) under node.
/// Regenerate: see scripts/verify_semver.mjs.
void main() {
  final raw = File('test/semver_vectors.json').readAsStringSync();
  final vectors = jsonDecode(raw) as Map<String, dynamic>;

  group('semverCoerce (verkit ground truth)', () {
    vectors['coerce']!.forEach((input, expected) {
      test('coerce($input) → $expected', () {
        final got = semverCoerce(input);
        expect(got?.toString(), expected);
      });
    });
  });

  group('satisfies (verkit ground truth)', () {
    for (final entry in (vectors['sat'] as List)) {
      final range = entry[0] as String;
      final version = entry[1] as String;
      final expected = entry[2];
      test('$version in "$range" → $expected', () {
        final parsed = SemVer.tryParse(version)!;
        if (expected == 'ERR') {
          // verkit threw on invalid input; we treat as non-match.
          expect(satisfies(parsed, range), isFalse);
        } else {
          expect(
            satisfies(parsed, range),
            expected,
            reason: '$version vs range "$range"',
          );
        }
      });
    }
  });

  group('semverSatisfies facade', () {
    test('mirrors hot-updater call order (coerce then satisfies)', () {
      expect(semverSatisfies('^1.2.0', 'v1.3.0'), isTrue);
      // coerce("1") -> 1.0.0 which does NOT match ^1.2.0 (verkit-verified).
      expect(semverSatisfies('^1.2.0', '1'), isFalse);
      // ...but ^1.0.0 matches coerced 1.0.0.
      expect(semverSatisfies('^1.0.0', '1'), isTrue);
      expect(semverSatisfies('^1.2.0', 'junk'), isFalse);
      expect(semverSatisfies('~2.3.4', 'app version 2.3.6!'), isTrue);
    });
  });
}
