import 'package:flutter_ota_kit/flutter_ota_kit.dart';

// Generated by `flutter-ota init supabase`.
//
// Non-secret values default to the project config (`.flutter_ota_kit/config.json`
// set up during init); every value can be overridden by a build-time
// `--dart-define` / `.env` (environment wins). Secrets (keys/tokens) are never
// hard-coded here — supply them via `.env`.
//
// Call [setupFlutterOta] once in `main()`, after
// WidgetsFlutterBinding.ensureInitialized() and before runApp(). It wires the
// supabase update source and enables zero-click forced updates (the process
// restarts automatically when a forced bundle is available).
Future<void> setupFlutterOta() async {
  FlutterPatcher.configureSupabase(SupabaseUpdateConfig(
     supabaseUrl: const String.fromEnvironment('SUPABASE_URL', defaultValue: ''),
     anonKey: const String.fromEnvironment('SUPABASE_ANON_KEY', defaultValue: ''),
     bucket: const String.fromEnvironment('SUPABASE_BUCKET', defaultValue: 'bundles'),
    channel: const String.fromEnvironment('CHANNEL', defaultValue: 'production'),
    platform: Platform.android,
    updateStrategy: UpdateStrategy.appVersion,
    appVersion: const String.fromEnvironment('APP_VERSION', defaultValue: ''),
    sdkVersion: const String.fromEnvironment('SDK_VERSION', defaultValue: '1.0.0'),
  ));
  await FlutterPatcher.init(autoApplyUpdates: true);
}
